<?php

/**
 * This is the model base class for the table "m_cash_flow".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MCashFlow".
 *
 * Columns in table "m_cash_flow" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $description
 * @property integer $category
 *
 */
abstract class BaseMCashFlow extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_cash_flow';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MCashFlow|MCashFlows', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, description, category', 'required'),
			array('category', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>5),
			array('description', 'length', 'max'=>50),
			array('id, code, description, category', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'description' => Yii::t('app', 'Description'),
			'category' => Yii::t('app', 'Category'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('category', $this->category);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}