<?php

/**
 * This is the model base class for the table "m_room_number".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MRoomNumber".
 *
 * Columns in table "m_room_number" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $room_number
 * @property integer $room_type
 * @property string $normal_rate_only
 * @property string $corporate_rate_only
 * @property string $breakfast_rate
 * @property string $normal_rate_include_breakfast
 * @property string $corporate_rate_include_breakfast
 *
 */
abstract class BaseMRoomNumber extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_room_number';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MRoomNumber|MRoomNumbers', $n);
	}

	public static function representingColumn() {
		return 'room_number';
	}

	public function rules() {
		return array(
			array('room_number, room_type, normal_rate_only, corporate_rate_only, breakfast_rate, normal_rate_include_breakfast, corporate_rate_include_breakfast', 'required'),
			array('room_type', 'numerical', 'integerOnly'=>true),
			array('room_number', 'length', 'max'=>6),
			array('normal_rate_only, corporate_rate_only, normal_rate_include_breakfast, corporate_rate_include_breakfast', 'length', 'max'=>20),
			array('breakfast_rate', 'length', 'max'=>10),
			array('id, room_number, room_type, normal_rate_only, corporate_rate_only, breakfast_rate, normal_rate_include_breakfast, corporate_rate_include_breakfast', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'room_number' => Yii::t('app', 'Room Number'),
			'room_type' => Yii::t('app', 'Room Type'),
			'normal_rate_only' => Yii::t('app', 'Normal Rate Only'),
			'corporate_rate_only' => Yii::t('app', 'Corporate Rate Only'),
			'breakfast_rate' => Yii::t('app', 'Breakfast Rate'),
			'normal_rate_include_breakfast' => Yii::t('app', 'Normal Rate Include Breakfast'),
			'corporate_rate_include_breakfast' => Yii::t('app', 'Corporate Rate Include Breakfast'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('room_number', $this->room_number, true);
		$criteria->compare('room_type', $this->room_type);
		$criteria->compare('normal_rate_only', $this->normal_rate_only, true);
		$criteria->compare('corporate_rate_only', $this->corporate_rate_only, true);
		$criteria->compare('breakfast_rate', $this->breakfast_rate, true);
		$criteria->compare('normal_rate_include_breakfast', $this->normal_rate_include_breakfast, true);
		$criteria->compare('corporate_rate_include_breakfast', $this->corporate_rate_include_breakfast, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}