<?php

/**
 * This is the model base class for the table "m_asset_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MAssetCategory".
 *
 * Columns in table "m_asset_category" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $asset_account_id
 * @property integer $acum_dep_account_id
 * @property string $cost_asset
 *
 */
abstract class BaseMAssetCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_asset_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MAssetCategory|MAssetCategories', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, name, asset_account_id, acum_dep_account_id, cost_asset', 'required'),
			array('asset_account_id, acum_dep_account_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>5),
			array('name', 'length', 'max'=>50),
			array('cost_asset', 'length', 'max'=>20),
			array('id, code, name, asset_account_id, acum_dep_account_id, cost_asset', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'asset_account_id' => Yii::t('app', 'Asset Account'),
			'acum_dep_account_id' => Yii::t('app', 'Acum Dep Account'),
			'cost_asset' => Yii::t('app', 'Cost Asset'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('asset_account_id', $this->asset_account_id);
		$criteria->compare('acum_dep_account_id', $this->acum_dep_account_id);
		$criteria->compare('cost_asset', $this->cost_asset, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}