<?php

/**
 * This is the model base class for the table "m_billing".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MBilling".
 *
 * Columns in table "m_billing" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $billing_name
 * @property integer $status_int
 * @property integer $revenue_account_id
 * @property integer $ar_account_id
 *
 */
abstract class BaseMBilling extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_billing';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MBilling|MBillings', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, billing_name, status_int, revenue_account_id, ar_account_id', 'required'),
			array('status_int, revenue_account_id, ar_account_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>5),
			array('billing_name', 'length', 'max'=>50),
			array('id, code, billing_name, status_int, revenue_account_id, ar_account_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'billing_name' => Yii::t('app', 'Billing Name'),
			'status_int' => Yii::t('app', 'Status Int'),
			'revenue_account_id' => Yii::t('app', 'Revenue Account'),
			'ar_account_id' => Yii::t('app', 'Ar Account'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('billing_name', $this->billing_name, true);
		$criteria->compare('status_int', $this->status_int);
		$criteria->compare('revenue_account_id', $this->revenue_account_id);
		$criteria->compare('ar_account_id', $this->ar_account_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}