<?php

/**
 * This is the model base class for the table "m_interest".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MInterest".
 *
 * Columns in table "m_interest" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $year
 * @property string $rate
 * @property integer $liability_account_id
 * @property integer $interest_revenue_account_id
 *
 */
abstract class BaseMInterest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_interest';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MInterest|MInterests', $n);
	}

	public static function representingColumn() {
		return 'rate';
	}

	public function rules() {
		return array(
			array('year, rate, liability_account_id, interest_revenue_account_id', 'required'),
			array('year, liability_account_id, interest_revenue_account_id', 'numerical', 'integerOnly'=>true),
			array('rate', 'length', 'max'=>10),
			array('id, year, rate, liability_account_id, interest_revenue_account_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'year' => Yii::t('app', 'Year'),
			'rate' => Yii::t('app', 'Rate'),
			'liability_account_id' => Yii::t('app', 'Liability Account'),
			'interest_revenue_account_id' => Yii::t('app', 'Interest Revenue Account'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('year', $this->year);
		$criteria->compare('rate', $this->rate, true);
		$criteria->compare('liability_account_id', $this->liability_account_id);
		$criteria->compare('interest_revenue_account_id', $this->interest_revenue_account_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}