<?php

/**
 * This is the model base class for the table "user_module".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserModule".
 *
 * Columns in table "user_module" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_level_id
 * @property integer $module_id
 *
 */
abstract class BaseUserModule extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_module';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserModule|UserModules', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_level_id, module_id', 'required'),
			array('user_level_id, module_id', 'numerical', 'integerOnly'=>true),
			array('id, user_level_id, module_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_level_id' => Yii::t('app', 'User Level'),
			'module_id' => Yii::t('app', 'Module'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_level_id', $this->user_level_id);
		$criteria->compare('module_id', $this->module_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}