<?php

/**
 * This is the model base class for the table "document_setting".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DocumentSetting".
 *
 * Columns in table "document_setting" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $module
 * @property string $prefix_code
 * @property integer $company_id
 * @property integer $numbering
 * @property integer $year
 * @property integer $month
 *
 */
abstract class BaseDocumentSetting extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'document_setting';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DocumentSetting|DocumentSettings', $n);
	}

	public static function representingColumn() {
		return 'module';
	}

	public function rules() {
		return array(
			array('module, prefix_code, company_id, numbering', 'required'),
			array('company_id, numbering, year, month', 'numerical', 'integerOnly'=>true),
			array('module', 'length', 'max'=>10),
			array('prefix_code', 'length', 'max'=>20),
			array('year, month', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, module, prefix_code, company_id, numbering, year, month', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'module' => Yii::t('app', 'Module'),
			'prefix_code' => Yii::t('app', 'Prefix Code'),
			'company_id' => Yii::t('app', 'Company'),
			'numbering' => Yii::t('app', 'Numbering'),
			'year' => Yii::t('app', 'Year'),
			'month' => Yii::t('app', 'Month'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('module', $this->module, true);
		$criteria->compare('prefix_code', $this->prefix_code, true);
		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('numbering', $this->numbering);
		$criteria->compare('year', $this->year);
		$criteria->compare('month', $this->month);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}