<?php

/**
 * This is the model base class for the table "m_service_tax".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MServiceTax".
 *
 * Columns in table "m_service_tax" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $tax_name
 * @property integer $rate
 * @property integer $tax_account_id
 *
 */
abstract class BaseMServiceTax extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_service_tax';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MServiceTax|MServiceTaxes', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, tax_name, rate, tax_account_id', 'required'),
			array('rate, tax_account_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>5),
			array('tax_name', 'length', 'max'=>50),
			array('id, code, tax_name, rate, tax_account_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'tax_name' => Yii::t('app', 'Tax Name'),
			'rate' => Yii::t('app', 'Rate'),
			'tax_account_id' => Yii::t('app', 'Tax Account'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('tax_name', $this->tax_name, true);
		$criteria->compare('rate', $this->rate);
		$criteria->compare('tax_account_id', $this->tax_account_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}