<?php

/**
 * This is the model base class for the table "m_extra_bed".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MExtraBed".
 *
 * Columns in table "m_extra_bed" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $pax
 * @property string $rate_per_pax
 *
 */
abstract class BaseMExtraBed extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_extra_bed';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MExtraBed|MExtraBeds', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('pax, rate_per_pax', 'required'),
			array('pax', 'numerical', 'integerOnly'=>true),
			array('rate_per_pax', 'length', 'max'=>20),
			array('id, pax, rate_per_pax', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pax' => Yii::t('app', 'Pax'),
			'rate_per_pax' => Yii::t('app', 'Rate Per Pax'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pax', $this->pax);
		$criteria->compare('rate_per_pax', $this->rate_per_pax, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}